/**
 * Automates the creation of barrel files for concept and synchronization
 * imports. It scans the concepts and syncs directories and generates:
 *  - `src/concepts/concepts.ts`: production concepts wired to the main database.
 *  - `src/concepts/test_concepts.ts`: concepts wired to a fresh test database.
 *  - `src/syncs/syncs.ts`: all discovered synchronizations.
 *
 * This enables convenient, typed imports like:
 *   `import { User, Post } from "@concepts";`
 *
 * Run this script using `bun run build`.
 */
import { readdirSync, statSync, writeFileSync } from "node:fs";
import * as path from "node:path";

const CONCEPTS_DIR = process.env.CONCEPTS_DIR ?? "src/concepts";
const SYNCS_DIR = process.env.SYNCS_DIR ?? "src/syncs";

interface ConceptInfo {
  /** PascalCase name, e.g. "User". */
  name: string;
  /** Original directory name, e.g. "User". */
  dirName: string;
  /** Relative import path, e.g. "./User/UserConcept.ts". */
  importPath: string;
}

/**
 * Discovers every valid concept: a directory `{name}` containing a
 * `{name}Concept.ts` file.
 */
function discoverConcepts(baseDir: string): ConceptInfo[] {
  const concepts: ConceptInfo[] = [];
  const absoluteBaseDir = path.resolve(baseDir);

  for (const entry of readdirSync(absoluteBaseDir, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;

    const conceptDirName = entry.name;
    const fileName = `${conceptDirName}Concept.ts`;
    const conceptFilePath = path.join(absoluteBaseDir, conceptDirName, fileName);

    if (!isFile(conceptFilePath)) continue;

    const conceptName = conceptDirName.charAt(0).toUpperCase() +
      conceptDirName.slice(1);
    concepts.push({
      name: conceptName,
      dirName: conceptDirName,
      importPath: `./${conceptDirName}/${fileName}`,
    });
    console.log(`  -> Found concept: ${conceptName}`);
  }
  return concepts;
}

/** Generates the content of a concepts barrel file (production or test). */
function generateBarrelFileContent(
  concepts: ConceptInfo[],
  isTest: boolean,
): string {
  const dbImportFunc = isTest ? "testDb" : "getDb";

  const header =
    `// This file is auto-generated by the \`generate_imports.ts\` script.
// Do not edit it manually, unless you know your concept requires a custom instantiation procedure.

import { SyncConcept } from "@engine";

export const Engine = new SyncConcept();
`;

  const dbImport = `import { ${dbImportFunc} } from "@utils/database.ts";\n`;

  const conceptClassImports = concepts
    .map((c) => `import ${c.name}Concept from "${c.importPath}";`)
    .join("\n");

  const conceptTypeExports = concepts
    .map(
      (c) =>
        `export type { default as ${c.name}Concept } from "${c.importPath}";`,
    )
    .join("\n");

  const dbInitialization = `
// Initialize the database connection
export const [db, client] = await ${dbImportFunc}();
`;

  const instantiations = concepts
    .map((c) =>
      `export const ${c.name} = Engine.instrumentConcept(new ${c.name}Concept(db));`
    )
    .join("\n");

  return [
    header,
    dbImport,
    conceptClassImports,
    "",
    conceptTypeExports,
    dbInitialization,
    instantiations,
    "",
  ].join("\n");
}

interface SyncInfo {
  /** Fully-qualified prefix, e.g. "auth.login". */
  prefix: string;
  /** Sanitized alias for import, e.g. "sync_auth_login". */
  importAlias: string;
  /** Relative import path, e.g. "./auth/login.sync.ts". */
  importPath: string;
}

/** Recursively discovers all `*.sync.ts` files under the given directory. */
function discoverSyncs(baseDir: string): SyncInfo[] {
  const absoluteBaseDir = path.resolve(baseDir);
  if (!isDirectory(absoluteBaseDir)) return [];

  const syncs: SyncInfo[] = [];
  for (const filePath of walk(absoluteBaseDir)) {
    if (!filePath.endsWith(".sync.ts")) continue;

    const relativePath = path.relative(absoluteBaseDir, filePath);
    const prefix = relativePath
      .replace(/\.sync\.ts$/, "")
      .replaceAll(path.sep, ".");
    const importAlias = `sync_${prefix.replaceAll(/[^a-zA-Z0-9]/g, "_")}`;
    const importPath = `./${relativePath.replaceAll(path.sep, "/")}`;

    syncs.push({ prefix, importAlias, importPath });
    console.log(`  -> Found sync file: ${relativePath}`);
  }
  return syncs;
}

/** Generates the content of the syncs barrel file. */
function generateSyncsBarrelFileContent(syncs: SyncInfo[]): string {
  const header =
    `// This file is auto-generated by the \`generate_imports.ts\` script.\n// Do not edit it manually.\n`;
  const typeImport = `import type { Sync } from "@engine";\n`;

  const syncImports = syncs
    .map((s) => `import * as ${s.importAlias} from "${s.importPath}";`)
    .join("\n");

  const instantiation = `\nconst allSyncs: Record<string, Sync> = {};\n`;

  const populationLogic = syncs
    .map(
      (s) => `
for (const [name, func] of Object.entries(${s.importAlias})) {
  if (typeof func === "function") {
    allSyncs[\`${s.prefix}.\${name}\`] = func as Sync;
  }
}`,
    )
    .join("");

  return [
    header,
    typeImport,
    syncImports,
    instantiation,
    populationLogic,
    "\nexport default allSyncs;\n",
  ].join("\n");
}

function isFile(p: string): boolean {
  try {
    return statSync(p).isFile();
  } catch {
    return false;
  }
}

function isDirectory(p: string): boolean {
  try {
    return statSync(p).isDirectory();
  } catch {
    return false;
  }
}

/** Yields every file path under `dir`, recursing into subdirectories. */
function* walk(dir: string): Generator<string> {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      yield* walk(full);
    } else if (entry.isFile()) {
      yield full;
    }
  }
}

function main(): void {
  console.log(`Scanning for concepts in '${CONCEPTS_DIR}'...`);
  const concepts = discoverConcepts(CONCEPTS_DIR);
  if (concepts.length === 0) {
    console.warn("Warning: No concepts found. Generated files will be empty.");
  }

  const prodFilePath = path.join(CONCEPTS_DIR, "concepts.ts");
  writeFileSync(prodFilePath, generateBarrelFileContent(concepts, false));
  console.log(`Generated production barrel file: ${prodFilePath}`);

  const testFilePath = path.join(CONCEPTS_DIR, "test_concepts.ts");
  writeFileSync(testFilePath, generateBarrelFileContent(concepts, true));
  console.log(`Generated test barrel file: ${testFilePath}`);

  console.log(`\nScanning for syncs in '${SYNCS_DIR}'...`);
  const syncs = discoverSyncs(SYNCS_DIR);
  if (syncs.length === 0) {
    console.warn("Warning: No syncs found. Generated syncs file will be empty.");
  }

  const syncsFilePath = path.join(SYNCS_DIR, "syncs.ts");
  writeFileSync(syncsFilePath, generateSyncsBarrelFileContent(syncs));
  console.log(`Generated syncs barrel file: ${syncsFilePath}`);
}

if (import.meta.main) {
  main();
}
